# Generated by Django 5.1 on 2024-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('JR', 'Junior'), ('GR', 'Graduate'), ('NE', 'Not Enrolled'), ('SR', 'Senior'), ('FR', 'Freshman'), ('SO', 'Sophomore')], max_length=2),
        ),
    ]
