# Generated by Django 5.1 on 2024-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('FR', 'Freshman'), ('JR', 'Junior'), ('GR', 'Graduate'), ('NE', 'Not Enrolled'), ('SR', 'Senior'), ('SO', 'Sophomore')], max_length=2),
        ),
    ]
