# Generated by Django 5.1 on 2024-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('NE', 'Not Enrolled'), ('JR', 'Junior'), ('GR', 'Graduate'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('SR', 'Senior')], max_length=2),
        ),
    ]
