# Generated by Django 5.1 on 2024-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('NE', 'Not Enrolled'), ('SO', 'Sophomore'), ('GR', 'Graduate'), ('JR', 'Junior'), ('SR', 'Senior'), ('FR', 'Freshman')], max_length=2),
        ),
    ]
