# Generated by Django 5.1 on 2024-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('SR', 'Senior'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('GR', 'Graduate'), ('JR', 'Junior'), ('NE', 'Not Enrolled')], max_length=2),
        ),
    ]
