# Generated by Django 5.1 on 2024-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('SO', 'Sophomore'), ('JR', 'Junior'), ('FR', 'Freshman'), ('GR', 'Graduate'), ('NE', 'Not Enrolled'), ('SR', 'Senior')], max_length=2),
        ),
    ]
