# Generated by Django 5.1 on 2024-04-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_alter_student_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('GR', 'Graduate'), ('NE', 'Not Enrolled'), ('SR', 'Senior'), ('FR', 'Freshman'), ('JR', 'Junior'), ('SO', 'Sophomore')], max_length=2),
        ),
    ]
